### ISSUE TITLE
Contacts.requestPermission callBack is not working in Android

### ISSUE THREAD

**Issue by ankit7878** [rt2zz/react-native-contacts#255] opened 2018-02-21 12:26 UTC
i have tested multiple time but it didn't work in android.
on Allow click it should call the callBack Function : 
Please see my code : 
```es
Contacts.checkPermission( (err, permission) => {
      if(permission === 'undefined' || permission === 'denied'){
        Contacts.requestPermission( (err, permission) => {
          console.log(permission);
          console.log('ITS SHOULD CALL THIS BLOCK OF CODE and i have tested many times but this call back function is not being executed first time in **Android only** when user click on allow permission.');
        })
      }
      if(permission === 'authorized'){
        console.log(permission);
      }
    });
```
**Is there any solution ?**

**Comment by yqbk** [comment] 2018-02-28 09:38
Any updates on that?

**Comment by zero1108** [comment] 2018-03-05 06:28
My condition is that the permission always return 'authorized'

**Comment by Ramaraju1992** [comment] 2018-03-15 07:04
@ankit7878 may be in your MainActivity.java or any other Activity classes you are requesting any other permissions... then result for permission request will go there.... check if you are using anywhere 

`@Override
    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
}`

**Comment by ankit7878** [comment] 2018-03-15 15:51
sorry for late reply but i will try to make an example repo for this issue ,so i will be easy for contributor to identify the exact issue 

and @Ramaraju1992 though i will check once again

**Comment by JoostVermeulen11** [comment] 2018-03-27 08:04
+1 For solution, had this issue too. Very annoying when things doesn't work as expected. Had to remove some native permission code in MainActivity.java to fix this.

**Comment by sinewave440hz** [comment] 2018-03-28 14:50
Any news on this? Regarding the comment by @Ramaraju1992 I have onRequestPermissionsResult in ImagePickerModule but that is not being called. Nor of course the one in ContactsManager in this project.

**Comment by sinewave440hz** [comment] 2018-04-03 14:34
There is a great workaround here in the meantime that completely solves the problem for me: https://github.com/rt2zz/react-native-contacts/issues/218#issuecomment-339489701

So I just kept this package's requestPermission() method in for non-android platforms and used the above for Android.

**Comment by morenoh149** [comment] 2018-04-05 14:26
closing as duplicate of #218 the recent versions of android require a different approach to permissions. When things are cleared up in #218 it'll get added to the docs.

**Closed by morenoh149** 2018-04-05 14:26 UTC

**Comment by GabrielDelight** [comment] 2023-08-01 07:28
I'm having this issue in 2023 lol can't resolve it, please I need help.
