### ISSUE TITLE
URGENT: iOS App Crash on startup

### ISSUE THREAD

**Issue by homertester** [rt2zz/react-native-contacts#239] opened 2017-12-08 15:04 UTC
Dear,

I have a strange problem:

When loading my contacts on an Iphone 6, running iOS 11.1.2, everything is working correctly.

But, when loading my contacts on an Iphone 8, running same the iOS 11.1.2, the app crashes completely.

What could be causing the issue?  
I'm running react native version 0.48.4.

Thanks in advance!

**Comment by morenoh149** [comment] 2017-12-08 19:15
No clue. Could you try reproducing the problem with https://github.com/morenoh149/react-native-contacts-test

**Comment by homertester** [comment] 2017-12-09 13:21
I think it's related to request of access permissions to the contacts... could this be possible?

**Comment by morenoh149** [comment] 2017-12-09 18:41
yes its possible, but I'm not sure

**Comment by zengkm** [comment] 2018-01-02 03:30
I met the same problem. Everything is correct in simulator, but in real devices,  when it goes to get contacts, app crashes.

**Comment by tomershohet** [comment] 2018-02-05 13:55
Have you added the request description to the Info.plist? ->
 
"An iOS app linked on or after iOS 10.0 must include in its Info.plist file the usage description keys for the types of data it needs to access or it will crash. To access Contacts data specifically, it must include NSContactsUsageDescription."

https://developer.apple.com/documentation/contacts

**Comment by UniverseHan** [comment] 2018-03-03 17:30
Is this thread should closed??

**Comment by morenoh149** [comment] 2018-03-03 17:54
Closing due to lack of details. If you can share a minimal example that reproduces the problem we can reopen.

**Closed by morenoh149** 2018-03-03 17:54 UTC

**Comment by zengkm** [comment] 2018-03-07 11:35
I found my problem when I debug with real device. It is caused by some data of null in contacts. You need to add some condition  to solve it.

**Comment by morenoh149** [comment] 2018-03-07 23:00
@zengkm We need to reproduce the issue. Please report back with the device model and screencaps and shared source code to reproduce.

**Comment by Renjithcse** [comment] 2019-07-27 07:17
I am using Iphone 8 and running OS IOS 13. I am trying to get allContacts in debug mode its working fine and return all contacts. But in release mode it was not working. It return only empty array.

**Comment by morenoh149** [comment] 2019-07-30 02:02
@Renjithcse does the app crash? if not then it should be a separate issue.
