### ISSUE TITLE
Thumbnail Paths changing?

### ISSUE THREAD

**Issue by berkaey** [rt2zz/react-native-contacts#84] opened 2016-08-13 11:26 UTC
Hey Im on iOS and trying to get images with thumbnailPath.

If I try to get image in a session which I get contacts info recently it just works, but if I close the app and open again or live reload etc. Images just return empty like no image but also no error.

Is this a bug or something I need to know. I can try to reach contact info everytime when app opening but it probably not a good idea. (it took 3sec to get 200 contacts) 

So what should I do, any idea? thanks.

**Comment by berkaey** [comment] 2016-08-13 11:29
I tested further, it happens only on a new bundle (like live reload,new build from xcode etc.) I guess.

**Comment by morenoh149** [comment] 2016-08-15 16:52
no clue

**Comment by mistenkt** [comment] 2016-09-19 13:53
Also have this issue. My listview will show the thumbnails on the first load. But if I exit the scene and then go back into it, the .png name (not the path) has changed and the thumbnail will not display.

**Comment by morenoh149** [comment] 2016-09-19 15:16
maybe ios is changing the paths based on the context. The ios code needs to use a different api if I'm not mistaken. It's currently using the addressBook api when it should be ported to use the Contacts api.

**Comment by npomfret** [comment] 2016-10-12 18:05
This API will (hopefully) be changing soon.  I think the new implementation will not suffer from this problem.  I think it's likely that the images are being placed in a temp folder which gets cleaned up between invocations of the app.  Storing the icon uri might not be possible, instead we're thinking of adding an API that will return the icon URI on demand.

**Comment by tomauty** [comment] 2016-10-17 14:13
Any updates on that? Will be a major help for my project :)

**Comment by npomfret** [comment] 2016-10-17 16:20
It's work in progress on my [fork](https://github.com/npomfret/react-native-contacts/tree/on-demand-thumbnail-creation).  If you have an opinion on what you think the API should be, or would like to help with testing it'd be appreciated.

Currently I think there should be:

 * default behaviour is to not create thumbnail due to the inherent performance problems
 * users should have the option to create thumbnails when they call `getAll`
 * `getAll` with thumbnail creation may have two options - to create the thumbnails synchronously or asynchronously 
 * there should a new api call (implemented in the fork already) to create a thumbnail on demand and return the path to it

**Comment by npomfret** [comment] 2017-03-14 15:16
Can we close?

**Comment by morenoh149** [comment] 2017-03-14 15:19
btw @npomfret you can close this issues right? I'm guessing you're asking the OP if the issue is resolved.

**Closed** 2017-03-14 15:19 UTC
Labels: ios

**Comment by npomfret** [comment] 2017-03-14 17:24
Yeah, just being polite that all.
